### PR TITLE
Save plots as pickled figures

### PR DESCRIPTION
**Pull request by joniemi**
When testing complex data, I find it helpful to navigate the produced figures using pyplot's interactive GUI interface. This pull request implements this feature by giving the option of storing figures in pickle files which can be loaded later for inspection. The option is triggered if a user defines an output filename with a ".pickle" suffix.

Would this feature be useful for a wider public?

I have not signed my name to the contributor list yet.

### CODE REVIEW

**Comment by hunse** [comment]
Hi @joniemi. Thanks for your contribution! I believe this could be useful to others.

Can you please sign the contributor's agreement by making a PR to add your name to [this list](https://www.nengo.ai/people/) (the [source file is here](https://github.com/nengo/nengo.github.io/blob/master/people.md))?

**Comment by hunse** [comment]
@joniemi Sorry, never mind! I was incorrect. Since this repo is under an open-source license, you don't need to sign the contributor's agreement.

**Comment by joniemi** [comment]
Thanks @hunse and @tbekolay! Looking forward to the next release. :)

**Comment by drasmuss** [comment]
`pytest-plt` 1.1.0 has now been released (containing this feature), thanks again!

**Pull request closed without merging**
