### PR TITLE
Call config.addini to eliminate warnings in downstream repos

### PR DESCRIPTION
**Pull request by tbekolay**
Warnings were being thrown in NengoCore because pytest-plt didn't call `config.addini` for configuration options.

This PR also updates to the lastest version of NengoBones.

### CODE REVIEW

**Comment by hunse** [comment]
These changes (e.g. using f-strings) will mean that we no longer support Python 3.5. I'm fine with this (I noticed you also changed the tests to no longer test 3.5, so I'm guessing you are too), but we should update both the min python version and the classifiers in nengobones.yml accordingly. (Also, assuming the tests pass on 3.8/3.9, we can add those classifiers.)

**Comment by tbekolay** [comment]
Yes, Python 3.5 is past its end of life so we have no plans to support it across any of our projects. The min Python version (in NengoBones) defaults to 3.6, but yes we should definitely change the classifiers. Made that change, and updated appveyor to hopefully pass this time ...

**Review by hunse — APPROVED** [review]
LGTM. I also tested locally that the config options still work.

Let me know when the tests pass and I'll merge.

**Comment by tbekolay** [comment]
CI is all passing now; coverage isn't being collected correctly, but I think we should not worry about that for now.

**Pull request merged**
